### ISSUE TITLE
DOCS: How to migrate existing lab storage quota to PHI

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#103]
(moving from #51) 

https://wynton.ucsf.edu/hpc/about/pricing-storage.html lacks info how to migrate existing lab storage quota to PHI.

**Comment by ellestad** [comment]
Added a FAQ section to the storage purchase page.

https://wynton.ucsf.edu/hpc/about/pricing-storage.html#frequently-asked-questions
