### ISSUE TITLE
Password Entry Confusing

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#141]
Some new Wynton users are confused that their password is not echoed to the screen as they type.

I think in the example from the getting started page, you should remove the Xs and specifically note that the password is not echoed to the screen.

https://wynton.ucsf.edu/hpc/get-started/access-cluster.html

```
{local}$ ssh alice@log1.wynton.ucsf.edu
alice@log1.wynton.ucsf.edu:s password: XXXXXXXXXXXXXXXXXXX
[alice@log1 ~]$ 
```

**Comment by HenrikBengtsson** [comment]
Good point. Fixed and added a sentence

**Comment by HenrikBengtsson** [comment]
Fixed more instances of this elsewhere, cf. commit 0daaf62
