### ISSUE TITLE
Clarify Storage/Quota Pages

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#45]
Clarify Storage and Quota Pages to indicate that they also apply to /wynton/protected.

* [x] https://wynton.ucsf.edu/hpc/howto/storage-size.html

* [x] https://wynton.ucsf.edu/hpc/about/pricing-storage.html

**Comment by HenrikBengtsson** [comment]
Completed, cf.

* https://github.com/ucsf-wynton/wynton-website-hpc/commit/85ba0043057e6e5091f75074577e620f9371b629
* https://github.com/ucsf-wynton/wynton-website-hpc/commit/ddf8eafadd41e91f85adaeca9c18584c79d00752

PS. @murashka-ucsf , please remember to close issues when you complete them
