### ISSUE TITLE
About Wynton site.cluster.name

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#49]
```{{site.cluster.name}}```
Showing up in the title of the User Agreement page on the website.

**Comment by ellestad** [comment]
![WyntonUserAgreement](https://user-images.githubusercontent.com/6099465/159368307-23d20743-c78e-4650-9fea-c75b7d1eca73.jpg)

**Comment by HenrikBengtsson** [comment]
Looks like one cannot use `# {{site.cluster.name}} yada yada`, because then that is included verbatim into the page title.  I simply dropped it, cf. commit 78123a7.
