### ISSUE TITLE
Notice for PHI Users

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#52]
One of the most common questions/frustrations is new PHI users trying to login to log1/log2.

Please make it clear in the "login & logout" page https://wynton.ucsf.edu/hpc/get-started/access-cluster.html doc that if you are a PHI Account, you need to use plog1.

Also on the development & prototyping page https://wynton.ucsf.edu/hpc/get-started/development-prototyping.html that you need to use pdev1/pgpudev1.

And add the PHI nodes to the specs page: https://wynton.ucsf.edu/hpc/about/specs.html

**Comment by HenrikBengtsson** [comment]
Good points. Somewhat related to #51

**Comment by HenrikBengtsson** [comment]
The new Non-PHI/PHI toggle switch (#51) addresses most of this. Let me know if it can be improved further.

**Comment by HenrikBengtsson** [comment]
> And add the PHI nodes to the specs page: https://wynton.ucsf.edu/hpc/about/specs.html

Now tracked in #102.

I think the other things are now completed by #51.
