### ISSUE TITLE
choulab Member Shares

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#55]
https://wynton.ucsf.edu/hpc/about/shares.html

There's something weird either with the choulab member shares, fshare value, or the outputting to the web page.

Usually there are three values in a line: Processing Units, Member.q Slots, and Lab Group

However, on the two choulab lines (why two lines?), there are only two values and the "Lab Group", "choulab" appears in the "Member.q Slots" column.

**Comment by ellestad** [comment]
```
[eje@q1 ~]$ qconf -sprj choulab
name choulab
oticket 0
fshare 1
acl choulab
xacl NONE
```
[eje@q1 ~]$ qconf -srqs member_queue_limits
{
   name         member_queue_limits
   description  "Limit labs to only their share in member.q"
   enabled      TRUE
[...]
   limit        projects choulab queues member.q to slots=6
[...]

**Comment by HenrikBengtsson** [comment]
The data rendered online is from <https://github.com/ucsf-wynton/wynton-website-hpc/blob/master/docs/assets/data/compute_shares.tsv>.  It's updated using a cronjob (running as `hb` on dev-1) using the `wynton-shares` (source code: <https://github.com/ucsf-wynton/wynton-tools/blob/master/bin/wynton-shares>) tool as:

```sh
$ module load CBI CBI-testing wynton-tools

 2022-05-05 12:13:50 ⌚  dev1 in ~
○ → wynton shares tsv
# Created by: hb
# Created on: 2022-05-05 12:14:06-07:00
# Total fshares: 20210
# Total queue_slots: 10268
# Number of projects: 53
fshares queue_slots     project
5506    3305    salilab
4104    1403    agardlab,chenglab,frostlab
1224    408     pollardlab
182     61      ichs
…
15      36      kroganlab
12      4       sysbiocenter
6       choulab
6       choulab
3       1       voigtlab
3       1       cohenlab
…
1       10      mcmanuslab
1       101     lynchlab
1       100     capralab
```

**Comment by HenrikBengtsson** [comment]
One step closer to the source of the problem:

```sh
$ wynton shares list --fshares --project choulab
fshares queue_slots project
     1           6 choulab
          6 choulab
```

**Comment by HenrikBengtsson** [comment]
It's probably because there are two `choulab` entries (the only project with this) in:

```sh
$ qconf -srqs member_queue_limits | grep choulab
   limit        projects choulab queues member.q to slots=6
   limit        projects choulab queues member.q to slots=6
```

**Comment by HenrikBengtsson** [comment]
Fixed website/tsv after making [wynton-shares robust against these qconf duplicates](https://github.com/ucsf-wynton/wynton-tools/commit/45d4e88edf515926b92028569c691bcc72cb4f8e).

**Comment by jlbl** [comment]
RQS fixed to remove duplicate entry.
