### ISSUE TITLE
NOTES: When can we drop mentioning of Windows 8 and PuTTY? [ANSWER: on 2023-01-10]

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#63]
I leave this here as a note for now, since I already looked it up.

# Notes

On https://wynton.ucsf.edu/hpc/get-started/access-cluster.html#prerequisites we write:

> Microsoft Windows 8 or older: If you are on Windows 8 or older, you do not have a built-in SSH client. If so, we recommend to install the [PuTTY](https://www.putty.org/) SSH client, which has slightly different command-line interface but it has full SSH support. Please consult the PuTTY documentation and user forums for further instructions. Another alternative, which some might find easier, is to connect to the cluster using the [X2Go](https://wynton.ucsf.edu/hpc/howto/gui-x11fwd.html) software.

On https://wynton.ucsf.edu/hpc/howto/log-in-without-pwd.html#instruction we write:

> These instructions are primarily written for Linux, macOS, and Windows 10 users. If you are on a pre-Windows 10, using the [PuTTY](https://www.putty.org/) SSH client, the overall idea is similar. Please consult the PuTTY user forums for further instructions.

* [x] According to https://docs.microsoft.com/en-us/lifecycle/products/windows-7, 'Mainstream' support for MS Windows 7 ended on 2015-01-13. The 'Extended' support ended of 2020-01-14. The 'Extended Security Update' runs for three years and ends on 2023-01-10.

* [x] According to https://docs.microsoft.com/en-us/lifecycle/products/windows-81, 'Mainstream' support for MS Windows 8.1 ended on 2018-01-09 (4.5 years ago!). The 'Extended' support ends on 2023-01-10.  ~~No mentioning of 'Extended Security Update', but if it's also three years, then it's end in January 2026.~~ There is no 'Extended Security Update' support for MS Windows 8 (https://support.microsoft.com/en-us/windows/windows-8-1-support-will-end-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93). MS Windows 8 is also at end-of-life as of 2023-01-10.

# Cleanup

_If_ we knew there are no users on MS Windows (<= 8.1), we could drop all of the above.  Since all MS Windows 10 users have built-in 'ssh' support, we no longer have to mention PuTTY (occurs in [1] and [2]).

However, I think UCSF IT might have 'Extended' support for MS Windows, so we probably have to keep it for a while longer.

**Comment by HenrikBengtsson** [comment]
FWIW, The 'Extended' support for MS Windows 7 ended on 2023-01-10 (yesterday), so at least we know it's very unlikely we have any users on MS Windows 7.

**Comment by ellestad** [comment]
I don't see why to take it out.

I hate the way cut and paste works from the Windows command line and prefer Putty myself.

I would just change it from:

"Microsoft Windows 8 or older: If you are on Windows 8 or older, you do not have a built-in SSH client. If so, we recommend to install the [PuTTY](https://www.putty.org/) SSH client, which has slightly different command-line interface but it has full SSH support. Please consult the PuTTY documentation and user forums for further instructions. Another alternative, which some might find easier, is to connect to the cluster using the [X2Go](https://wynton.ucsf.edu/hpc/howto/gui-x11fwd.html) software."

To something like:

"You can also use the [PuTTY](https://www.putty.org/) SSH client or another ssh client if you prefer. If you choose to use another ssh client, consult that program's documentation for further instructions. Another alternative, which some might find easier, is to connect to the cluster using the [X2Go](https://wynton.ucsf.edu/hpc/howto/gui-x11fwd.html) software."

**Comment by HenrikBengtsson** [comment]
> I don't see why to take it out.

Basically, minimize the amount of tools that needs to be supported and that are part of the equation when troubleshooting.  This is especially true when it comes to setting up SSH keys, cf. the https://www.c4.ucsf.edu/howto/log-in-without-pwd.html page.

> I hate the way cut and paste works from the Windows command line and prefer Putty myself.

FWIW, are you aware of [Microsoft Terminal](https://en.wikipedia.org/wiki/Windows_Terminal)?  It's modern, full-featured terminal, so no need to use the clunky cmd.exe these days. It supports selecting with the mouse, Ctrl-C, Ctrl-V, etc. and all keyboard shortcuts can be customized to whatever you like.

I'm okay to keep mentioning PuTTY, but I think we should drive traffic to the no common `ssh` command-line tool.

**Comment by HenrikBengtsson** [comment]
UPDATE: Turns out that there is no 'Extended Security Update' support for MS Windows 8 (https://support.microsoft.com/en-us/windows/windows-8-1-support-will-end-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93), i.e. both MS Windows 7 and MS Windows 8 are at end-of-life as of 2023-01-10.

**Comment by HenrikBengtsson** [comment]
I've updated relevant pages accordingly, cf. commit 3bd7a6b.
