### ISSUE TITLE
Check errors that needs to be fixed

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#68]
@murashka-ucsf , can you please fix these asap, since they're cluttering check feedback to others:

* https://github.com/ucsf-wynton/wynton-website-hpc/actions/runs/2490405349
* https://github.com/ucsf-wynton/wynton-website-hpc/actions/runs/2490405357

**Comment by murashka-ucsf** [comment]
closing.

added words to WORDLIST.

Fixed MarkdownLint "no hard tabs" issue (originally had cut & pasted from elsewhere. rather than typed those in).
