### ISSUE TITLE
Update Globus User Documentation on Website

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#70]
Terminology has changed in the Globus Webapp, update website to reflect, primarily as regards collections vs endpoints.
Also, update the URL for the "UCSF Wynton HPC" collection to the new globus v5 collection.

**Comment by ellestad** [comment]
@HenrikBengtsson I am not sure how the {{ site.globus.uuid }} for the "UCSF Wynton HPC" variable is populated. Needs to be updated to: 68f06816-cd00-4bf3-ae1f-0597a07ed118

**Comment by HenrikBengtsson** [comment]
> @HenrikBengtsson I am not sure how the {{ site.globus.uuid }} for the "UCSF Wynton HPC" collection is populated. Needs to be updated to: 68f06816-cd00-4bf3-ae1f-0597a07ed118

All `site.*` variables are set in https://github.com/ucsf-wynton/wynton-website-hpc/blob/master/docs/_config.yml

**Comment by ellestad** [comment]
Thanks, I've fixed that, I think.

**Comment by ellestad** [comment]
replaced "endpoint/s" with "Collection/s".

**Comment by ellestad** [comment]
Fixed all broken Globus URLs due to collection UUID changes.
