### ISSUE TITLE
Disk quota: "Generally, single labs/groups should be group quota."(?!?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#71]
I'm cleaning up and clarifying the disk quota page. ~~@mhucsf~~ @murashka-ucsf what does:

```
Generally, single labs/groups should be group quota. 
```

trying to convey? (cf. https://github.com/ucsf-wynton/wynton-website-hpc/commit/85ba0043057e6e5091f75074577e620f9371b629)

**Comment by HenrikBengtsson** [comment]
There's also:

```
PHI/Projects are for IRBs that are either subgroups of the lab/group
or supergroups that encompass more than one group.
```

What's the message to the users here?  I'm not sure if they know what "supergroups" are (I don't).    Can you please expand on this to make it clearer to the reader?

Also, `PHI/Projects` is a typo for `PHI projects`, correct?  Or, is it a formal term?

**Comment by HenrikBengtsson** [comment]
> I wonder if @HenrikBengtsson tagged me by mistake. I have nothing to add about this topic.

Sorry, I'm certainly not the first doing this, and I won't be the last.

@murashka-ucsf , if you don't mind, could you please add at least your first name to your GitHub Profile; that'll lower the risk for these mistakes.

**Comment by HenrikBengtsson** [comment]
A friendly reminder about this "unclear" sentence on <https://wynton.ucsf.edu/hpc/howto/storage-size.html#group-disk-quota-on-wyntongroup-and-wyntonprotectedproject>

**Comment by ellestad** [comment]
I took a shot at cleaning this section up:

https://wynton.ucsf.edu/hpc/howto/storage-size.html#group-disk-quota-on-wyntongroup-and-wyntonprotectedproject

**Comment by HenrikBengtsson** [comment]
Thanks. There are a few places on the page that says things like:

> Group folder under (i.e. /wynton/group/ and /wynton/protected/project/)

That sounds like there are two storage group areas, but there are three, correct? E.g. /wynton/group/boblab/, /wynton/protected/group/boblab/, and /wynton/protected/project/bobsproject/.

**Comment by ellestad** [comment]
Yes, but if it is in /wynton/protected/project/, it will be separate group/quota from the combined /wynton/group/ and /wynton/protected/group/ quota.

**Comment by HenrikBengtsson** [comment]
> Yes, but if it is in /wynton/protected/project/, it will be separate ...

Would it make sense to have a separate section on the page for such project-specific folders then?

BTW, right now it sounds project foldersv are only for PHI, but I'd imagine someone would ask for the same also for non-PHI.

Also, would it make sense to say regular group folders have a much longer life cycle than project folders?

**Comment by HenrikBengtsson** [comment]
> BTW, right now it sounds as if project folders are only for PHI, but I'd imagine someone would ask for the same also for non-PHI.

From the last Wynton meeting (2023-01-23), I learned that we only got PHI project folders.  There's no such thing as a non-PHI project folder.
