### ISSUE TITLE
Globus File Sharing Out of Sync?

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#77]
The website page at: https://wynton.ucsf.edu/hpc/transfers/globus-sharing.html 

Is out of sync with the updates on: https://github.com/ucsf-wynton/wynton-website-hpc/blob/master/docs/transfers/globus-sharing.md

Any idea why?

**Comment by HenrikBengtsson** [comment]
Should not be possible, because Jekyll servers the HTML based on the markdown file. Also, skimming the two files, I cannot see what's missing - what words/paragraphs differ?

**Comment by ellestad** [comment]
Oh, I see, I never did fix that "click the activate button" thing in step 3. My mistake.
