### ISSUE TITLE
JHub: Three Python code snippets - should be one?!?

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#81]
On https://wynton.ucsf.edu/hpc/howto/jupyterhub.html, there are three code Python snippets next to each other:

```python
from dask_jobqueue import SGECluster
from dask.distributed import Client

cluster = SGECluster(queue = "short.q",
...
```

and

```python
import os

# Set environment variables
os.environ["SGE_ROOT"] = "/opt/sge"
```

and

```python
cluster.scale(2) # number of workers needed for your job
client = Client(cluster)
client
```

Should those be one big Python code block?

**Comment by HenrikBengtsson** [comment]
Also, is `import os` needed when one uses `os.environ`?

**Comment by HenrikBengtsson** [comment]
friendly ping @sakethkoduru

**Comment by HenrikBengtsson** [comment]
Another ping @sakethkoduru - let me know if you need to discuss this.

**Comment by sakethkoduru** [comment]
> Also, is `import os` needed when one uses `os.environ`?

yes

**Comment by sakethkoduru** [comment]
> On https://wynton.ucsf.edu/hpc/howto/jupyterhub.html, there are three code Python snippets next to each other:
> 
> ```python
> from dask_jobqueue import SGECluster
> from dask.distributed import Client
> 
> cluster = SGECluster(queue = "short.q",
> ...
> ```
> 
> and
> 
> ```python
> import os
> 
> # Set environment variables
> os.environ["SGE_ROOT"] = "/opt/sge"
> ```
> 
> and
> 
> ```python
> cluster.scale(2) # number of workers needed for your job
> client = Client(cluster)
> client
> ```
> 
> Should those be one big Python code block
Since users run this in Jupyter Notebook instead of a Python script, I have split the code in three different snippets each would go in a cell on Jupyter Notebook.

**Comment by HenrikBengtsson** [comment]
I see.  Anyway, when I try to follow the instruction on <https://wynton.ucsf.edu/hpc/howto/jupyterhub.html> in JHub, I get:

```python
from dask_jobqueue import SGECluster

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-75fe7dab8e8b> in <module>
----> 1 from dask_jobqueue import SGECluster

ModuleNotFoundError: No module named 'dask_jobqueue'
```

It looks like instructions for installing Dask are missing.

**Comment by HenrikBengtsson** [comment]
Moot. Jupyter Hub has been discontinued.
