### ISSUE TITLE
Update GPU Page

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#84]
qb3-atgpu18 should be noted as an MSG GPU node on the GPU page.

**Comment by ellestad** [comment]
qb3-atgpu15 and qb3-atgpu17 will be re-assigned as app servers to Adam Yala and will no longer be available as institutional GPUs.

**Comment by HenrikBengtsson** [comment]
I've just explained how to do this in https://github.com/ucsf-wynton/wynton-website-hpc/issues/85#issuecomment-1276597566. Please give it a try.

**Comment by HenrikBengtsson** [comment]
Thanks.  While at it, what the 'NVME Status' for `msg-iogpu7` is unknown.  Could you please identify what it should and fix that too?

**Comment by ellestad** [comment]
Should note which GPU nodes are exclusively available in the 4gpu.q (and include a link to the information about submitting to the 4gpu.q).

**Comment by HenrikBengtsson** [comment]
> Thanks. While at it, what the 'NVME Status' for `msg-iogpu7` is unknown. Could you please identify what it should be and fix that too?

In addition to this, there's also one `48GiB` cell that should be `48 GiB`.

**Comment by HenrikBengtsson** [comment]
> Should note which GPU nodes are exclusively available in the 4gpu.q (and include a link to the information about submitting to the 4gpu.q)

This information is on, yet-to-be-released <https://wynton.ucsf.edu/hpc/about/gpu-shares.html>.  When approved (#24), I think we should merge that page into the existing <https://wynton.ucsf.edu/hpc/about/gpus.html> page.

**Comment by HenrikBengtsson** [comment]
Also, there's no `jacobson` group - it should be `jacobsonlab`, cf.

```
$ SGE_SINGLE_LINE=true qconf -srqs shared_gpu_limits
{
   name         shared_gpu_limits
   description  "Limits on use of owned GPUs by non-owners"
   enabled      TRUE
   limit        projects {!rosenberglab} queues gpu.q hosts {@rosenberglabgpunodes} to h_rt=7200
   limit        projects {!agardlab,!chenglab,!frostlab,!stroudlab,!gpu-collab} queues gpu.q hosts {@msggpunodes} to h_rt=7200
   limit        projects {!agardlab,!chenglab,!frostlab,!stroudlab,!gpu-collab} queues 4gpu.q hosts {@msg4gpunodes} to h_rt=7200
   limit        projects {!grabelab} queues gpu.q hosts {@grabelabgpunodes} to h_rt=7200
   limit        projects {!genetics,!arnaoutlab} queues gpu.q hosts qb3-iogpu1 to h_rt=7200
   limit        projects {!huanglab} queues gpu.q hosts {@huanglabgpunodes} to h_rt=7200
   limit        projects {!jacobsonlab,!arnaoutlab} queues gpu.q hosts qb3-idgpu6 to h_rt=7200
   limit        projects {!gladstone,!pollardlab} queues gpu.q hosts {@gladstonegpunodes} to h_rt=7200
   limit        projects {!i4h} queues gpu.q hosts {@i4hgpunodes} to h_rt=7200
   limit        projects {!keiserlab} queues gpu.q hosts qb3-atgpu16 to h_rt=7200
   limit        projects {!ichs} queues gpu.q hosts qb3-atgpu19 to h_rt=7200
   limit        projects {!theodorislab} queues gpu.q hosts qb3-atgpu20 to h_rt=7200
   limit        projects {!neuroppg} queues gpu.q hosts qb3-atgpu21 to h_rt=7200
   limit        projects {!gidb} queues gpu.q hosts qb3-atgpu22 to h_rt=7200
   limit        projects {!rsl} queues gpu.q hosts qb3-atgpu23 to h_rt=7200
}
```

Please check the others too.

**Comment by HenrikBengtsson** [comment]
@murashka-ucsf , can you please fix the above GPU mistakes?

**Comment by murashka-ucsf** [comment]
Fixed msg-iogpu7 scratch info
Fixed jacobson -> jacobson lab typo
Fixed 48GiB -> 48 GiB typo

**Comment by Nicki-Martin** [comment]
Closing - fixed manually
