### ISSUE TITLE
How to update table of GPU nodes

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#85]
The process for updating the GPU page should be documented. Looks like it is some sort of java database?

**Comment by HenrikBengtsson** [comment]
I assume you're talking about the table on https://wynton.ucsf.edu/hpc/about/gpus.html.  It's not a "java database", but a tab-delimited file that is read and rendered by JavaScript running in the web browser.  I try to give minimal clues to reads and editors at the bottom of table to give them an idea when and how it's updated.  In this case there's:

> Source: [gpu_nodes.tsv](https://wynton.ucsf.edu/hpc/assets/data/gpu_nodes.tsv) produced on 2022-05-13. These data are manually updated.

The file to update in this repo is https://github.com/ucsf-wynton/wynton-website-hpc/blob/master/docs/assets/data/gpu_nodes.tsv

**Comment by Nicki-Martin** [comment]
@murashka-ucsf will update.  Check for changes quarterly and update to keep it current.

**Comment by murashka-ucsf** [comment]
Added

```
qb3-atgpu20
qb3-atgpu21
qb3-atgpu22
qb3-atgpu23
qb3-atgpu24
```

Removed `qb3-atgpu15` and `qb3-atgpu17` since those have become `yala-app1` and `yala-app2` app servers.
