### ISSUE TITLE
UCSF Password Wiki Link Not Public

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#86]
The link on the Wynton [Change password page](https://wynton.ucsf.edu/hpc/howto/change-pwd.html) to the UCSF password policy goes to a page on the UCSF Wiki which requires authentication.

As not all Wynton Users are UCSF Users, should a summary of the actual Wynton password policy be listed on the Wynton password page?

Or to a public page with the UCSF policy?

Something like: [UCSF Password InfoGraphic](https://it.ucsf.edu/sites/itw/files/inline-files/Password%20Infographic%20v2.pdf)

**Comment by ellestad** [comment]
As far as I can tell, the password comes out of '/etc/security/pwquality.conf' on Alexander and Aristotle.

**Comment by HenrikBengtsson** [comment]
Oh my, that's really silly of them to hide that behind a login. I guess we could request them to release those rules to the world, but that's probably a big uphill.

So, yes, we could explicitly document this on the Wynton page, e.g.

> The password should fulfill the following requirements, which follows the [UCSF Enterprise Password Standard](https://wiki.library.ucsf.edu/pages/viewpage.action?spaceKey=ITSI&title=Unified+UCSF+Enterprise+Password+Standard):
>
> * ...
> * ...
> * ...

PS. Remember this issue tracker is public to the world.

**Comment by HenrikBengtsson** [comment]
> Or to a public page with the UCSF policy?
> 
> Something like: [UCSF Password InfoGraphic](https://it.ucsf.edu/sites/itw/files/inline-files/Password%20Infographic%20v2.pdf)

That's the quick solution. I'd say go for it (although it's a PDF, which might not be accessible)

**Comment by Nicki-Martin** [comment]
Agreed to keep it as is until we hear users having issues
