### ISSUE TITLE
Conda: additional info to add

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#90]
Document also:

* [x] how to update packages in a conda environment
* [x] how to remove an environment
* [x] Mention Python-versioned environment creations, e.g. `-n myjupyter-py38 notebook python=3.8` 
* [ ] Link to Conda cheat sheet, e.g. <https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf>
* [x] how to remove automatic activation of the 'base' environment in `~/.bashrc` (default behavior for most users who installed Conda by themselves)
* [x] Under the section "Creating a Conda environment (required)", [...] include a sentence that "By default, the environment is created in the user's home directory. To create the environment at a specific location, refer to the [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)."

/ht @kvale, @AshirBorah, @ayushi-agrawal-gladstone

**Comment by AshirBorah** [comment]
Also addition of the python version parameter while creating the environment

**Comment by HenrikBengtsson** [comment]
I'm punting on linking to a Conda Cheat Sheet, mainly because it seems hard to find a persistent link to one. Don't want to link to a hard-coded version, because that risks being outdated.
