### ISSUE TITLE
ssh-keygen: explain how to create ~/.ssh

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-wynton/wynton-website-hpc#91]
<https://wynton.ucsf.edu/hpc/howto/log-in-without-pwd.html> does not show how to create `~/.ssh`.  
The instructions should be so that the correct file permissions are set.  How do we do that on MS Windows 10?

**Comment by ellestad** [comment]
No special permissions need to be set on the .ssh directory on the Windows ssh client side, the default permissions should be fine.

It is usually the permissions on the .ssh directory on the Unix server side that are problematic. 

They should be 700, but the default umask, if the user creates the .ssh directory manually, are 755.

**Comment by ellestad** [comment]
Though, the instructions should be changed to use the FQDN of log1 in this step, as the short name will not work from most laptops.
```
{local}$ scp ~/.ssh/laptop_to_wynton.pub alice@log1:.ssh/
laptop_to_wynton.pub           100%  390     0.4KB/s   00:00
```

**Comment by HenrikBengtsson** [comment]
> the instructions should be changed to use the FQDN of log1

Thx. Fixed
