### ISSUE TITLE
Remove COVID Alert Header?

### ISSUE THREAD

**Issue by ellestad** [ucsf-wynton/wynton-website-hpc#93]
Remove this, now that we are heading towards whatever is the "new normal"?

"2020-03-16: We will do our best to keep the Wynton HPC environment up and running within the restrictions imposed by UCSF and local governments. Minor issues (like node crashes) will be dealt with at a later date. Major issues will be dealt with on a best-effort basis and may result in longer than normal outages (especially if they require someone to be on site). Email response times are likely to be slower, as well, as we all struggle to adapt to the impacts of COVID-19."

**Comment by HenrikBengtsson** [comment]
I agree. Just drop it, or do we need to discuss with the Wynton Team?

**Comment by ellestad** [comment]
Removed alert header from:

https://github.com/ucsf-wynton/wynton-website-hpc/blob/master/docs/hpc/index.md
